/* eslint-disable no-unused-vars */
export default {
  up: (queryInterface, Sequelize) => queryInterface.bulkInsert(
    'users',
    [
      {
        id: 20,
        googleId: '1086917833519265752779',
        firstName: 'John',
        lastName: 'wick',
        email: 'johnwick@gmail.com',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 21,
        googleId: '1086917833519265752778',
        firstName: 'James',
        lastName: 'Bond',
        email: 'jamesbond@gmail.com',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 22,
        googleId: '1086917833519265752776',
        firstName: 'Julius',
        lastName: 'Jaja',
        email: 'juliusjaja@gmail.com',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 23,
        googleId: '1086917833519265752777',
        firstName: 'Jack',
        lastName: 'Patrick',
        email: 'jackpatrick@gmail.com',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 24,
        googleId: '1086917833519265752775',
        firstName: 'Jeff',
        lastName: 'Besos',
        email: 'jeffbesos@gmail.com',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 26,
        googleId: '1086917833519265752774',
        firstName: 'Bill',
        lastName: 'Gates',
        email: 'billgates@gmail.com',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 27,
        googleId: '1086917833519265752773',
        firstName: 'Mark',
        lastName: 'Zuckerberg',
        email: 'markzuck@gmail.com',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 28,
        googleId: '1086917833519265752772',
        firstName: 'Cobey',
        lastName: 'Briant',
        email: 'cobeybriant@gmail.com',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 29,
        googleId: '1086917833519265752771',
        firstName: 'Tonny',
        lastName: 'Stark',
        email: 'tonntstark@gmail.com',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 30,
        googleId: '1086917833519265752770',
        firstName: 'Steve',
        lastName: 'Rogers',
        email: 'steverogers@gmail.com',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 31,
        googleId: '1086917833519265752769',
        firstName: 'Peter',
        lastName: 'Parker',
        email: 'peterparker@gmail.com',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 32,
        googleId: '1086917833519265752768',
        firstName: 'Theodore',
        lastName: 'Roosevelt',
        email: 'theodoreroosevelt@gmail.com',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 33,
        googleId: '1086917833519265752767',
        firstName: 'William',
        lastName: 'Shakespeare',
        email: 'williamshakespeare@gmail.com',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 34,
        googleId: '1086917833519265752766',
        firstName: 'Albert',
        lastName: 'Einstein',
        email: 'alberteinstein@gmail.com',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 35,
        googleId: '1086917833519265752765',
        firstName: 'Elon',
        lastName: 'Musk',
        email: 'elonmusk@gmail.com',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 36,
        firstName: 'Niyonzi',
        lastName: 'Raufu',
        email: 'nraufu@gmail.com',
        googleId: '1086917800519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 37,
        firstName: 'Anisie',
        lastName: 'Anisie',
        email: 'auwimana@aimsammi.org',
        googleId: '1086917801519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 38,
        firstName: 'Cherubin',
        lastName: 'Ndikubwayo',
        email: 'cherubinkubwayo@gmail.com',
        googleId: '1086917802519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 39,
        firstName: 'Irene',
        lastName: 'Rukumbuzi',
        email: 'rukkirene21@gmail.com',
        googleId: '1086917803519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 40,
        firstName: 'Innocent',
        lastName: 'Ingabire',
        email: 'inno100os@gmail.com',
        googleId: '1086917804519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 41,
        firstName: 'Theoneste',
        lastName: 'Nsanzabarinda',
        email: 'theoneste99@gmail.com',
        googleId: '1086917805519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 42,
        firstName: 'MUKUNZI',
        lastName: 'THOMAS',
        email: 'mukmaforo@gmail.com',
        googleId: '1086917806519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 43,
        firstName: 'Patience Ishimwe',
        lastName: 'Iradukunda',
        email: 'brownpatience66@gmail.com',
        googleId: '1086917807519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 44,
        firstName: 'Alain Mucyo',
        lastName: 'Mfurayacu',
        email: 'alainmucyo3@gmail.com',
        googleId: '1086917808519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 45,
        firstName: 'Janvier Ntwali',
        lastName: 'Habiyaremye',
        email: 'janvierntwali@gmail.com',
        googleId: '1086917809519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 46,
        firstName: 'Ndatimana',
        lastName: 'Gilbert',
        email: 'gilbeltelnino@gmail.com',
        googleId: '1086917810519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 47,
        firstName: 'Ndikumana',
        lastName: 'Alexis',
        email: 'nklbigone@gmail.com',
        googleId: '1086917811519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 48,
        firstName: 'Solange',
        lastName: 'Iyubu',
        email: 'solangeiyubu@gmail.com',
        googleId: '1086917812519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 49,
        firstName: 'David',
        lastName: 'Uwayezu',
        email: 'daviduwayezu400@gmail.com',
        googleId: '1086917813519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 50,
        firstName: 'Mucyo Aime',
        lastName: 'Christian',
        email: 'christianmucyo49@gmail.com',
        googleId: '1086917814519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 51,
        firstName: 'Nyagatare',
        lastName: 'James',
        email: 'nyagatarejames@gmail.com',
        googleId: '1086917815519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 52,
        firstName: 'Umutesi',
        lastName: 'Nadine',
        email: 'tesskay4@gmail.com',
        googleId: '1086917816519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 53,
        firstName: 'Niwemutoni',
        lastName: 'Gatera Alice',
        email: 'alicegatera15@gmail.com',
        googleId: '1086917817519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 54,
        firstName: 'Ntirenganya',
        lastName: 'Rene Promesse',
        email: 'nrenejordan1@gmail.com',
        googleId: '1086917818519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 55,
        firstName: 'Steven',
        lastName: 'Mugabo',
        email: 'stevenmug143@gmail.com',
        googleId: '1086917819519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 56,
        firstName: 'Ami Des Jeunes',
        lastName: 'Habumugisha',
        email: 'habajeunes2@gmail.com',
        googleId: '1086917820519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 57,
        firstName: 'Fidele Brown',
        lastName: 'Cyemezo',
        email: 'cyemezobrown@gmail.com',
        googleId: '1086917821519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 58,
        firstName: 'Irenne',
        lastName: 'Cyusa Jacob',
        email: 'cyusa03@gmail.com',
        googleId: '1086917822519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 59,
        firstName: 'Mugiraneza',
        lastName: 'Jackson',
        email: 'jackswalter7@gmail.com',
        googleId: '1086917823519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 60,
        firstName: 'Herve',
        lastName: 'Musangwa',
        email: 'hervnzig1@gmail.com',
        googleId: '1086917824519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 61,
        firstName: 'Ineza',
        lastName: 'Bonté Grévy',
        email: 'inezabonte@gmail.com',
        googleId: '1086917825519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 62,
        firstName: 'Olivier',
        lastName: 'Nshimiyimana',
        email: 'onshimiye17@gmail.com',
        googleId: '1086917826519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 63,
        firstName: 'Berwa ',
        lastName: 'Aime Noel NIYITEGEKA',
        email: 'berwanoel@gmail.com',
        googleId: '1086917827519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 64,
        firstName: 'Faisal',
        lastName: 'CYIMANA',
        email: 'cyimanafaisal@gmail.com',
        googleId: '1086917828519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 65,
        firstName: 'Blaise ',
        lastName: 'Niyonkuru',
        email: 'blaiseniyonkuru12@gmail.com',
        googleId: '1086917829519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 66,
        firstName: 'Frank',
        lastName: 'MUNGERI',
        email: 'mungerifrank@gmail.com',
        googleId: '1086917830519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 67,
        firstName: 'Achille',
        lastName: 'Cishahayo Songa',
        email: 'songachillethe1her@gmail.com',
        googleId: '1086917831519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 68,
        firstName: 'Kevin ',
        lastName: 'Rodrigue Shema BIVEGETE',
        email: 'kevinshema5@gmail.com',
        googleId: '1086917832519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 69,
        firstName: 'Claude',
        lastName: 'Mukiza',
        email: 'mukizaclaude1@gmail.com',
        googleId: '1086917833519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 70,
        firstName: 'Loic',
        lastName: 'Hirwa Cardinal',
        email: 'cardinaloichirwa@gmail.com',
        googleId: '1086917834519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 71,
        firstName: 'edgar',
        lastName: 'shumbusho',
        email: 'shumbushoedgar@gmail.com',
        googleId: '1086917835519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 72,
        firstName: 'Deo',
        lastName: 'Niyonsaba Mugabo ',
        email: 'mugabodeo6@gmail.com',
        googleId: '1086917836519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 73,
        firstName: 'Flower',
        lastName: 'Umurerwa Lynda',
        email: 'umurerwalynda@gmail.com',
        googleId: '1086917837519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 74,
        firstName: 'Giles',
        lastName: 'Kabano',
        email: 'gilleskaba@gmail.com',
        googleId: '1086917838519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 75,
        firstName: 'Didace',
        lastName: 'Furebo ',
        email: 'furebodidace582@gmail.com',
        googleId: '1086917839519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 76,
        firstName: 'Jean Claude',
        lastName: 'Siboniyo ',
        email: 'siboniyojeanclaude@gmail.com',
        googleId: '1086917840519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 77,
        firstName: 'Jean Pierre',
        lastName: ' Imanirumva',
        email: 'jp.irumva@gmail.com',
        googleId: '1086917841519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 78,
        firstName: 'Janvier',
        lastName: 'Habineza',
        email: 'habinezajanvier688@gmail.com',
        googleId: '1086917842519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 79,
        firstName: 'Floris',
        lastName: 'Ngendahayo',
        email: 'florisngendahayo@gmail.com',
        googleId: '1086917843519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 80,
        firstName: 'Valens',
        lastName: 'Nsengimana',
        email: 'nsengvalens4@gmail.com',
        googleId: '1086917844519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 81,
        firstName: 'Eric',
        lastName: 'Amani ',
        email: 'amaniericus@gmail.com',
        googleId: '1086917845519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 82,
        firstName: 'Emmanuel',
        lastName: 'Dushimme',
        email: 'dushimeemma@gmail.com',
        googleId: '1086917846519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 83,
        firstName: 'Faith',
        lastName: 'Ryumugabe',
        email: 'fryumugabe@gmail.com',
        googleId: '1086917847519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 84,
        firstName: 'Adadie',
        lastName: 'Kashumba Junior ',
        email: 'junioradadie@gmail.com',
        googleId: '1086917848519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 85,
        firstName: 'Elvis',
        lastName: 'Iraguha',
        email: 'iraguhaelvis@gmail.com',
        googleId: '1086917849519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 86,
        firstName: 'Christian',
        lastName: 'Manzi',
        email: 'manzichristian07@gmail.com',
        googleId: '1086917850519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 87,
        firstName: 'Roger clement',
        lastName: 'Ngabonziza',
        email: 'cleronga@yahoo.fr',
        googleId: '1086917851519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 88,
        firstName: 'Dusabeyezu',
        lastName: 'Florentine',
        email: 'dusaflora2@gmail.com',
        googleId: '1086917852519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 89,
        firstName: 'Nshimiyimana cyusa',
        lastName: 'Kheven',
        email: 'cyusa.khevin100@gmail.com',
        googleId: '1086917853519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 90,
        firstName: 'Ndanyuzwe',
        lastName: 'Duncan',
        email: 'semunda9@gmail.com',
        googleId: '1086917854519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 91,
        firstName: 'Niyonkuru',
        lastName: 'Adolphe',
        email: 'adolniy01@gmail.com',
        googleId: '1086917855519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 92,
        firstName: 'Thierry',
        lastName: 'Ntirandekura',
        email: 'thierry.ntirandekura18@kepler.org',
        googleId: '1086917856519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 93,
        firstName: 'Herve',
        lastName: 'Butera',
        email: 'h.buterak@gmail.com',
        googleId: '1086917857519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 94,
        firstName: 'Bizimana',
        lastName: 'Gelio',
        email: 'geliobizimana01@gmail.com',
        googleId: '1086917858519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 95,
        firstName: 'Maxime',
        lastName: 'Ishimwe',
        email: 'mxmishimwe5@gmail.com',
        googleId: '1086917859519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 96,
        firstName: 'Jules',
        lastName: 'Ntare',
        email: 'julesntare@gmail.com',
        googleId: '1086917860519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 97,
        firstName: 'Ange',
        lastName: 'Ingabire',
        email: 'ange.ingabire07@gmail.com',
        googleId: '1086917861519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 98,
        firstName: 'Isaac',
        lastName: 'Komezusenge',
        email: 'isaackomeza@gmail.com',
        googleId: '1086917862519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 99,
        firstName: 'Marius',
        lastName: 'Robert Rwandarushya',
        email: 'rwandarushyarobert@gmail.com',
        googleId: '1086917863519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 100,
        firstName: 'Fiston',
        lastName: 'Habimana ',
        email: 'fistonhn@gmail.com',
        googleId: '1086917864519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 101,
        firstName: 'Patrick',
        lastName: 'Irankunda',
        email: 'irankundapatrick01@gmail.com',
        googleId: '1086917865519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 102,
        firstName: 'Fiacre',
        lastName: 'Igiraneza',
        email: 'fiacregiraneza@gmail.com',
        googleId: '1086917866519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 103,
        firstName: 'Johnson',
        lastName: 'Dusabe',
        email: 'johnsondusabe@gmail.com',
        googleId: '1086917867519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 104,
        firstName: 'Simon',
        lastName: 'Imanigirimpuhwe',
        email: 'mpuhwesimon06@gmail.com',
        googleId: '1086917868519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 105,
        firstName: 'Jean fidele',
        lastName: 'MUSIRIKARE',
        email: 'musirikarejf@gmail.com',
        googleId: '1086917869519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 106,
        firstName: 'Constantine',
        lastName: 'Maliza',
        email: 'malizacoco4@gmail.com',
        googleId: '1086917870519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 107,
        firstName: 'Barnardo',
        lastName: 'Ntaganira Herve',
        email: 'hervebardo@gmail.com',
        googleId: '1086917871519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 108,
        firstName: 'Jean marie vianney',
        lastName: 'Hategekimana',
        email: 'hategekamvianney@gmail.com',
        googleId: '1086917872519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 109,
        firstName: 'Patrick',
        lastName: 'Niyogitare',
        email: 'patrickniyogitare28@gmail.com',
        googleId: '1086917873519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 110,
        firstName: 'Niyitegeka',
        lastName: 'Marcel',
        email: 'niyitegekamar@outlook.com',
        googleId: '1086917874519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 111,
        firstName: 'Leny pascal',
        lastName: 'IHIRWE',
        email: 'lihirwe6@gmail.com',
        googleId: '1086917875519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 112,
        firstName: 'Samuel',
        lastName: 'Nshumbushijwenayo',
        email: 'nshusamuel1@gmail.com',
        googleId: '1086917876519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 113,
        firstName: 'Jemima',
        lastName: 'Nyirasafari',
        email: 'jemmyarina@gmail.com',
        googleId: '1086917877519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 114,
        firstName: 'Leonidas',
        lastName: 'Mugema',
        email: 'mugemaleo@gmail.com',
        googleId: '1086917878519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 115,
        firstName: 'Happiness',
        lastName: 'Karigirwa',
        email: 'happyka52@gmail.com',
        googleId: '1086917879519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 116,
        firstName: 'Xavier',
        lastName: 'Ncuti ',
        email: 'ncuti60@gmail.com',
        googleId: '1086917880519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 117,
        firstName: 'Emmanuel',
        lastName: 'Nkubito',
        email: 'emmanuelnkubito2@gmail.com',
        googleId: '1086917881519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 118,
        firstName: 'Josue',
        lastName: 'Karangwa Ntwali',
        email: 'josh1234king@gmail.com',
        googleId: '1086917882519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 119,
        firstName: 'Anastase',
        lastName: 'Tuyizere ',
        email: 'tuyizereanastase1@gmail.com',
        googleId: '1086917883519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 120,
        firstName: 'Gerard',
        lastName: 'Niyiragira ',
        email: 'niyiragiragerard@gmail.com',
        googleId: '1086917884519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 121,
        firstName: 'Egide',
        lastName: 'Isabwe',
        email: 'egide.isabwe@gmail.com',
        googleId: '1086917885519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 122,
        firstName: 'Nsabimana',
        lastName: 'Issa',
        email: 'mansurissa6@gmail.com',
        googleId: '1086917886519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 123,
        firstName: 'Samuel',
        lastName: 'HABINEZA',
        email: 'hbnzsml@gmail.com',
        googleId: '1086917887519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 124,
        firstName: 'Ntare',
        lastName: 'Guy Elkana',
        email: 'gntare2@gmail.com',
        googleId: '1086917888519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 125,
        firstName: 'Ngendahimana',
        lastName: 'Joseph',
        email: 'ngendajo@gmail.com',
        googleId: '1086917889519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 126,
        firstName: 'Guevara',
        lastName: 'Marius Irabizi',
        email: 'irabizimguevara@gmail.com',
        googleId: '1086917890519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 127,
        firstName: 'Kundwa',
        lastName: 'BRUNO MATERNE',
        email: 'kundwabruno@gmail.com',
        googleId: '1086917891519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 128,
        firstName: 'Tuyizere',
        lastName: 'Leonce',
        email: 'leoncetuyizere@gmail.com',
        googleId: '1086917892519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 129,
        firstName: 'Benoit',
        lastName: 'HABINEZA',
        email: 'habinezab1988@gmail.com',
        googleId: '1086917893519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 130,
        firstName: 'Ally',
        lastName: 'Nengo ',
        email: 'el.ally741@gmail.com',
        googleId: '1086917894519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 131,
        firstName: 'Elysee',
        lastName: 'Nishimwe',
        email: 'nishimwelys@gmail.com',
        googleId: '1086917895519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 132,
        firstName: 'Bizimungu',
        lastName: 'Pascal',
        email: 'bizip04@gmail.com',
        googleId: '1086917896519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 133,
        firstName: 'Hubert',
        lastName: 'Hirwa',
        email: 'hirwahubert2@gmail.com',
        googleId: '1086917897519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 134,
        firstName: 'Robert',
        lastName: 'Niyitanga',
        email: 'robertwilly668@gmail.com',
        googleId: '1086917898519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 135,
        firstName: 'Kaberuka',
        lastName: 'Freddy',
        email: 'freddykaberuka2009@gmail.com',
        googleId: '1086917899519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 136,
        firstName: 'Umuhire',
        lastName: 'Heritier',
        email: 'muhire416@gmail.com',
        googleId: '1086917900519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 137,
        firstName: 'Faustin',
        lastName: 'Ukundimana',
        email: 'fukundimana@gmail.com',
        googleId: '1086917901519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 138,
        firstName: 'Mugisha',
        lastName: 'Olivier',
        email: 'mugishaolivier198@gmail.com',
        googleId: '1086917902519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 139,
        firstName: 'Umutesi Glory',
        lastName: 'Princess',
        email: 'setpascal27@gmail.com',
        googleId: '1086917903519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 140,
        firstName: 'Ndagijimana',
        lastName: 'Sebastien',
        email: 'ndase15ba@gmail.com',
        googleId: '1086917904519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 141,
        firstName: 'Remy',
        lastName: 'Ihabwikuzo',
        email: 'rikuzo36@gmail.com',
        googleId: '1086917905519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 142,
        firstName: 'Iradukunda',
        lastName: 'Irenee ',
        email: 'iradukundairenee9@gmail.com',
        googleId: '1086917906519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 143,
        firstName: 'Bertin ',
        lastName: 'NDAYISHIMIYE',
        email: 'neddybertin@gmail.com',
        googleId: '1086917907519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 144,
        firstName: 'Bernard ',
        lastName: 'ISHIMWE',
        email: 'isbernard2001@gmail.com',
        googleId: '1086917908519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 145,
        firstName: 'Christian',
        lastName: 'Shema Mugisha',
        email: 'azertshema@gmail.com',
        googleId: '1086917909519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 146,
        firstName: 'Alex',
        lastName: 'Ndayishimiye',
        email: 'alexisvacilli1@gmail.com',
        googleId: '1086917910519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 147,
        firstName: 'Edmond ',
        lastName: 'Ndayishimiye',
        email: 'ndedmondus97@gmail.com',
        googleId: '1086917911519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 148,
        firstName: 'Patrick',
        lastName: 'NSHIMIYIMANA',
        email: 'lennoxmupi@gmail.com',
        googleId: '1086917912519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 149,
        firstName: 'Celestin ',
        lastName: 'Niyindagiriye',
        email: 'cniyindagiriye@gmail.com',
        googleId: '1086917913519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 150,
        firstName: 'Jules',
        lastName: 'hirwa habakaramo',
        email: 'hirwajulees@gmail.com',
        googleId: '1086917914519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 151,
        firstName: 'Maurice',
        lastName: 'Senzeyi',
        email: 'senzeyima@ueab.ac.ke',
        googleId: '1086917915519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 152,
        firstName: 'Jeannnette',
        lastName: 'Uwamahoro',
        email: 'uwamahorojanet88@gmail.com',
        googleId: '1086917916519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 153,
        firstName: 'Esli ',
        lastName: 'NSENGIYUMVA',
        email: 'nssli2@yahoo.fr',
        googleId: '1086917917519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 154,
        firstName: 'CEDRICK',
        lastName: 'MUPENZI',
        email: 'mcstain1639@gmail.com',
        googleId: '1086917918519265652766',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },

    ],
    {},
  ),

  down: (queryInterface, Sequelize) => queryInterface.bulkDelete('users', null, {}),
};
