/* eslint-disable no-unused-vars */
export default {
  up: (queryInterface, Sequelize) => queryInterface.bulkInsert(
    'users',
    [
      {
        id: 20,
        googleId: '1086917833519265752779',
        firstName: 'John',
        lastName: 'wick',
        email: 'johnwick@gmail.com',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 21,
        googleId: '1086917833519265752778',
        firstName: 'James',
        lastName: 'Bond',
        email: 'jamesbond@gmail.com',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 22,
        googleId: '1086917833519265752776',
        firstName: 'Julius',
        lastName: 'Jaja',
        email: 'juliusjaja@gmail.com',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 23,
        googleId: '1086917833519265752777',
        firstName: 'Jack',
        lastName: 'Patrick',
        email: 'jackpatrick@gmail.com',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 24,
        googleId: '1086917833519265752775',
        firstName: 'Jeff',
        lastName: 'Besos',
        email: 'jeffbesos@gmail.com',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 26,
        googleId: '1086917833519265752774',
        firstName: 'Bill',
        lastName: 'Gates',
        email: 'billgates@gmail.com',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 27,
        googleId: '1086917833519265752773',
        firstName: 'Mark',
        lastName: 'Zuckerberg',
        email: 'markzuck@gmail.com',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 28,
        googleId: '1086917833519265752772',
        firstName: 'Cobey',
        lastName: 'Briant',
        email: 'cobeybriant@gmail.com',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 29,
        googleId: '1086917833519265752771',
        firstName: 'Tonny',
        lastName: 'Stark',
        email: 'tonntstark@gmail.com',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 30,
        googleId: '1086917833519265752770',
        firstName: 'Steve',
        lastName: 'Rogers',
        email: 'steverogers@gmail.com',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 31,
        googleId: '1086917833519265752769',
        firstName: 'Peter',
        lastName: 'Parker',
        email: 'peterparker@gmail.com',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 32,
        googleId: '1086917833519265752768',
        firstName: 'Theodore',
        lastName: 'Roosevelt',
        email: 'theodoreroosevelt@gmail.com',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 33,
        googleId: '1086917833519265752767',
        firstName: 'William',
        lastName: 'Shakespeare',
        email: 'williamshakespeare@gmail.com',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 34,
        googleId: '1086917833519265752766',
        firstName: 'Albert',
        lastName: 'Einstein',
        email: 'alberteinstein@gmail.com',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 35,
        googleId: '1086917833519265752765',
        firstName: 'Elon',
        lastName: 'Musk',
        email: 'elonmusk@gmail.com',
        role: 'Trainee',
        createdAt: new Date(),
        updatedAt: new Date(),
      },

    ],
    {},
  ),

  down: (queryInterface, Sequelize) => queryInterface.bulkDelete('users', null, {}),
};
